name: github pages

on:
  push:
    branches:
      - master  # Set a branch to deploy
  repository_dispatch:  # Allow access tokens which have write access to this repo to trigger this action
  workflow_dispatch:  # Allow manual triggering by a user with write access to this repo

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          # fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          path: docs_root

      - name: Checkout charts repo
        uses: actions/checkout@v2
        with:
          repository: 'Australian-Imaging-Service/charts'
          # fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
          path: charts

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.4.13
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: npm ci
        working-directory: ./docs_root

      - name: Build
        working-directory: ./docs_root
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs_root/public
